version: '3.7'

services:
  db:
    container_name: test-database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - back_network
    ports:
      - "5432:5432"

  back:
    image: angro-backend
    container_name: angro-back
    working_dir: /usr/src/app/
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - back-static:/usr/src/app/allstaticfiles
      - back-media:/usr/src/app/media
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ENGINE=${ENGINE}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db
    networks:
      - back_network

networks:
  back_network:
    driver: bridge

volumes:
  postgres_data:
  back-static:
  back-media:
