version: '3.7'

services:
  db:
    container_name: test-database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
    - back_network

  back:
    image: angro-backend
    container_name: angro-back
    working_dir: /usr/src/app/
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - back-static:/usr/src/app/allstaticfiles
      - back-media:/usr/src/app/media
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - ENGINE=django.db.backends.postgresql_psycopg2
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
      - BACKEND_DOMAIN=${BACKEND_DOMAIN}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db
    networks:
      - back_network

networks:
  back_network:
    driver: bridge

volumes:
  postgres_data:
  back-static:
  back-media:
